In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/vrajesh0sharma7/salary-prediction-250k/job_salary.csv

In [2]:
data = pd.read_csv('/kaggle/input/datasets/vrajesh0sharma7/salary-prediction-250k/job_salary.csv')
data.sample(10)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
146623,Software Engineer,13,Diploma,12,Technology,Enterprise,UK,No,5,183689
77606,Backend Developer,5,PhD,15,Education,Startup,India,Hybrid,0,81040
199626,Backend Developer,7,PhD,8,Technology,Medium,Netherlands,Hybrid,2,142791
224372,Product Manager,18,Master,6,Technology,Startup,India,Hybrid,3,103081
39540,Cloud Engineer,1,Bachelor,12,Technology,Small,Sweden,No,2,99681
202410,Frontend Developer,3,Bachelor,5,Retail,Large,Netherlands,No,2,100649
41588,DevOps Engineer,16,Master,19,Finance,Enterprise,India,Hybrid,3,142125
151749,AI Engineer,0,Master,10,Technology,Startup,Singapore,No,0,112247
243350,Data Analyst,13,Master,17,Manufacturing,Medium,Germany,No,4,142866
146113,Business Analyst,4,PhD,14,Technology,Startup,Canada,Yes,0,126159

In [3]:
len(data.job_title.unique())

12

In [4]:
from keras.utils import to_categorical

data = pd.get_dummies(data, columns=['job_title','industry','location','remote_work'],dtype='int')
data

2026-04-13 09:23:56.381488: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1776072236.612811      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1776072236.679267      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1776072237.175780      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776072237.175816      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776072237.175819      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776072237.175821      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

,experience_years,education_level,skills_count,company_size,certifications,salary,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,10,Bachelor,2,Medium,2,109413,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,5,Bachelor,17,Small,0,93764,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,18,PhD,4,Medium,1,148123,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3,19,PhD,13,Medium,0,189123,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,15,Bachelor,7,Large,0,165069,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,17,PhD,2,Enterprise,1,127791,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
249996,20,PhD,7,Startup,2,154593,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
249997,1,Bachelor,12,Enterprise,0,75988,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
249998,0,High School,2,Small,5,90467,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
249999,16,Diploma,2,Medium,5,133084,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0

In [5]:
data['education_level'] = pd.factorize(data['education_level'])[0]
data['company_size'] = pd.factorize(data['company_size'])[0]
data

,experience_years,education_level,skills_count,company_size,certifications,salary,job_title_AI Engineer,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,...,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_Hybrid,remote_work_No,remote_work_Yes
0,10,0,2,0,2,109413,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,5,0,17,1,0,93764,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,18,1,4,0,1,148123,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
3,19,1,13,0,0,189123,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,15,0,7,2,0,165069,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,17,1,2,3,1,127791,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
249996,20,1,7,4,2,154593,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
249997,1,0,12,3,0,75988,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
249998,0,2,2,1,5,90467,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
249999,16,3,2,0,5,133084,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0

In [47]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
pd.DataFrame(data_scaled)

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,-0.000892,-1.415072,-1.459647,-1.412742,-0.288272,-0.970520,3.306966,-0.303808,-0.300046,-0.300347,...,3.007021,-0.332303,-0.333815,-0.333593,-0.334074,-0.332792,-0.332822,1.412400,-0.708938,-0.704370
1,-0.825894,-1.415072,1.277940,-0.704677,-1.460281,-1.388854,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,-0.333815,-0.333593,-0.334074,-0.332792,-0.332822,-0.708015,1.410560,-0.704370
2,1.319111,-0.708558,-1.094636,-1.412742,-0.874276,0.064289,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,-0.333815,2.997669,-0.334074,-0.332792,-0.332822,-0.708015,1.410560,-0.704370
3,1.484112,-0.708558,0.547917,-1.412742,-1.460281,1.160315,-0.302392,-0.303808,3.332823,-0.300347,...,-0.332555,-0.332303,-0.333815,-0.333593,-0.334074,-0.332792,-0.332822,-0.708015,-0.708938,1.419709
4,0.824110,-1.415072,-0.547118,0.003387,-1.460281,0.517295,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,-0.333815,-0.333593,2.993353,-0.332792,-0.332822,-0.708015,-0.708938,1.419709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,1.154111,-0.708558,-1.459647,0.711452,-0.874276,-0.479233,-0.302392,-0.303808,-0.300046,-0.300347,...,3.007021,-0.332303,-0.333815,-0.333593,-0.334074,-0.332792,-0.332822,-0.708015,1.410560,-0.704370
249996,1.649112,-0.708558,-0.547118,1.419516,-0.288272,0.237247,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,2.995675,-0.333593,-0.334074,-0.332792,-0.332822,-0.708015,1.410560,-0.704370
249997,-1.485896,-1.415072,0.365411,0.711452,-1.460281,-1.864048,-0.302392,-0.303808,3.332823,-0.300347,...,3.007021,-0.332303,-0.333815,-0.333593,-0.334074,-0.332792,-0.332822,-0.708015,-0.708938,1.419709
249998,-1.650897,-0.002043,-1.459647,-0.704677,1.469741,-1.476991,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,-0.333815,-0.333593,2.993353,-0.332792,-0.332822,1.412400,-0.708938,-0.704370
249999,0.989110,0.704471,-1.459647,-1.412742,1.469741,-0.337738,-0.302392,-0.303808,-0.300046,-0.300347,...,-0.332555,-0.332303,-0.333815,-0.333593,-0.334074,3.004877,-0.332822,-0.708015,1.410560,-0.704370

In [48]:
X = data.iloc[:, :-1]
y = data.iloc[:,-1]

X.shape,y.shape

((250000, 40), (250000,))

In [7]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [50]:
X_train.shape,y_train.shape

((200000, 40), (200000,))

In [51]:
model = Sequential()

model.add(Dense(64,activation='relu',input_shape=(40,)))
model.add(Dense(128,activation='relu'))
model.add(Dense(512,activation='relu'))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [52]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 64)             │         2,624 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,073 (43.25 KB)

 Trainable params: 11,073 (43.25 KB)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.compile(loss='mse',optimizer='adam',metrics=['mae'])

In [37]:
model.fit(X_train,y_train,epochs=10,validation_split=0.2)

Epoch 1/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 15s 3ms/step - loss: 12756121.0000 - mae: 576.3813 - val_loss: 96.4914 - val_mae: 9.4784
Epoch 2/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 9466.5059 - mae: 13.4304 - val_loss: 0.5121 - val_mae: 0.5350
Epoch 3/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 657.8389 - mae: 5.4392 - val_loss: 0.9788 - val_mae: 0.8584
Epoch 4/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 20.6892 - mae: 1.7485 - val_loss: 0.3755 - val_mae: 0.3946
Epoch 5/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 2.4328 - mae: 0.7250 - val_loss: 0.2413 - val_mae: 0.3926
Epoch 6/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2223 - mae: 0.4393 - val_loss: 0.2212 - val_mae: 0.4431
Epoch 7/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2223 - mae: 0.4443 - val_loss: 0.2216 - val_mae: 0.4358
Epoch 8/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2214 - mae: 0.4422 - val_loss: 0.2217 - val_mae: 0.4351
Epoch 9/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2210 - mae: 0.4415 - val_loss: 0.2213 - val_mae: 0.4395
Epoch 10/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2224 - mae: 0.4439 - val_loss: 0.2214 - val_mae: 0.4372

In [55]:
model.fit(X_train,y_train,epochs=10,validation_split=0.2)

Epoch 1/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 12.9215 - mae: 2.0397 - val_loss: 0.2697 - val_mae: 0.3237
Epoch 2/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 3.5127 - mae: 1.0687 - val_loss: 0.5963 - val_mae: 0.6426
Epoch 3/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 3.6860 - mae: 1.1307 - val_loss: 0.5373 - val_mae: 0.6298
Epoch 4/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 2.2938 - mae: 1.0932 - val_loss: 13.5418 - val_mae: 3.5346
Epoch 5/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - loss: 1.3068 - mae: 0.7572 - val_loss: 0.6242 - val_mae: 0.6782
Epoch 6/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.6617 - mae: 0.5200 - val_loss: 0.2328 - val_mae: 0.4760
Epoch 7/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.5155 - mae: 0.4446 - val_loss: 0.2222 - val_mae: 0.4529
Epoch 8/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2219 - mae: 0.4439 - val_loss: 0.2212 - val_mae: 0.4422
Epoch 9/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2219 - mae: 0.4435 - val_loss: 0.2213 - val_mae: 0.4387
Epoch 10/10
5000/5000 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - loss: 0.2214 - mae: 0.4423 - val_loss: 0.2213 - val_mae: 0.4457