In [3]:
import pandas as pd
import numpy as np

In [28]:
txt = pd.read_csv('/content/harry_potter_books.txt')

In [5]:
txt.sample(10)

,text,book,chapter
19939,did he run?` Harry had been wondering the sam...,Book 3: Prisoner of Azkaban,chap-14
51641,"Hall, where they could hear nothing except the...",Book 5: Order of the Phoenix,chap-19
52974,"meetings, haven't we?' 'You know what I mea...",Book 5: Order of the Phoenix,chap-21
3611,"know about it, Weasley, you couldn't afford ha...",Book 1: Philosopher's Stone,chap-10
4480,this had been his father's. He let the materia...,Book 1: Philosopher's Stone,chap-12
67238,boxes he was still clutching as he fumbled wit...,Book 6: Half Blood Prince,chap-6
46933,"Harry loudly, his fist in the air again. Pr...",Book 5: Order of the Phoenix,chap-12
20316,"certainly did,` said Snape, his face contorted...",Book 3: Prisoner of Azkaban,chap-14
74081,"bowed low over Hepzibah's fat little hand, bru...",Book 6: Half Blood Prince,chap-20
72043,"tree. Finally, he decided on the truth ... or ...",Book 6: Half Blood Prince,chap-16

In [6]:
len(txt)

95085

In [29]:
X = txt['text']
X

0        THE BOY WHO LIVED  Mr. and Mrs. Dursley, of nu...
1        four, Privet Drive, were proud to say that the...
2        thank you very much. They were the last people...
3        be involved in anything strange or mysterious,...
4        with such nonsense.  Mr. Dursley was the direc...
                               ...
95080    son glide away from him....The last trace of s...
95081    autumn air. The train rounded a corner. Harry'...
95082    in farewell.`He'll be alright,` murmured Ginny...
95083    his hand absentmindedly and touched the lightn...
95084    he will.`The scar had not pained Harry for nin...
Name: text, Length: 95085, dtype: object

In [30]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)

In [32]:
len(tokenizer.word_index)

25134

In [33]:
input_sequences = []
for sentence in X:
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [12]:
input_sequences

[[1, 269],
 [1, 269, 46],
 [1, 269, 46, 1310],
 [1, 269, 46, 1310, 121],
 [1, 269, 46, 1310, 121, 2],
 [1, 269, 46, 1310, 121, 2, 169],
 [1, 269, 46, 1310, 121, 2, 169, 1360],
 [1, 269, 46, 1310, 121, 2, 169, 1360, 4],
 [1, 269, 46, 1310, 121, 2, 169, 1360, 4, 641],
 [441, 1351],
 [441, 1351, 1044],
 [441, 1351, 1044, 35],
 [441, 1351, 1044, 35, 1913],
 [441, 1351, 1044, 35, 1913, 3],
 [441, 1351, 1044, 35, 1913, 3, 168],
 [441, 1351, 1044, 35, 1913, 3, 168, 16],
 [441, 1351, 1044, 35, 1913, 3, 168, 16, 23],
 [441, 1351, 1044, 35, 1913, 3, 168, 16, 23, 35],
 [441, 1351, 1044, 35, 1913, 3, 168, 16, 23, 35, 1209],
 [441, 1351, 1044, 35, 1913, 3, 168, 16, 23, 35, 1209, 1105],
 [795, 13],
 [795, 13, 74],
 [795, 13, 74, 146],
 [795, 13, 74, 146, 23],
 [795, 13, 74, 146, 23, 35],
 [795, 13, 74, 146, 23, 35, 1],
 [795, 13, 74, 146, 23, 35, 1, 141],
 [795, 13, 74, 146, 23, 35, 1, 141, 164],
 [795, 13, 74, 146, 23, 35, 1, 141, 164, 496],
 [795, 13, 74, 146, 23, 35, 1, 141, 164, 496, 840],
 [795, 13, 74, 146, 23, 35, 1, 141, 164, 496, 840, 3],
 [31, 2442],
 [31, 2442, 11],
 [31, 2442, 11, 195],
 [31, 2442, 11, 195, 997],
 [31, 2442, 11, 195, 997, 94],
 [31, 2442, 11, 195, 997, 94, 2657],
 [31, 2442, 11, 195, 997, 94, 2657, 174],
 [31, 2442, 11, 195, 997, 94, 2657, 174, 23],
 [31, 2442, 11, 195, 997, 94, 2657, 174, 23, 68],
 [31, 2442, 11, 195, 997, 94, 2657, 174, 23, 68, 109],
 [31, 2442, 11, 195, 997, 94, 2657, 174, 23, 68, 109, 745],
 [22, 481],
 [22, 481, 3565],
 [22, 481, 3565, 121],
 [22, 481, 3565, 121, 1360],
 [22, 481, 3565, 121, 1360, 8],
 [22, 481, 3565, 121, 1360, 8, 1],
 [22, 481, 3565, 121, 1360, 8, 1, 12698],
 [22, 481, 3565, 121, 1360, 8, 1, 12698, 4],
 [22, 481, 3565, 121, 1360, 8, 1, 12698, 4, 5],
 [22, 481, 3565, 121, 1360, 8, 1, 12698, 4, 5, 3827],
 [356, 10791],
 [356, 10791, 100],
 [356, 10791, 100, 157],
 [356, 10791, 100, 157, 6280],
 [356, 10791, 100, 157, 6280, 6],
 [356, 10791, 100, 157, 6280, 6, 8],
 [356, 10791, 100, 157, 6280, 6, 8, 5],
 [356, 10791, 100, 157, 6280, 6, 8, 5, 729],
 [356, 10791, 100, 157, 6280, 6, 8, 5, 729, 10792],
 [356, 10791, 100, 157, 6280, 6, 8, 5, 729, 10792, 281],
 [356, 10791, 100, 157, 6280, 6, 8, 5, 729, 10792, 281, 22],
 [776, 159],
 [776, 159, 665],
 [776, 159, 665, 1280],
 [776, 159, 665, 1280, 6],
 [776, 159, 665, 1280, 6, 70],
 [776, 159, 665, 1280, 6, 70, 36],
 [776, 159, 665, 1280, 6, 70, 36, 5],
 [776, 159, 665, 1280, 6, 70, 36, 5, 74],
 [776, 159, 665, 1280, 6, 70, 36, 5, 74, 220],
 [776, 159, 665, 1280, 6, 70, 36, 5, 74, 220, 2248],
 [776, 159, 665, 1280, 6, 70, 36, 5, 74, 220, 2248, 169],
 [1360, 8],
 [1360, 8, 707],
 [1360, 8, 707, 2],
 [1360, 8, 707, 2, 2925],
 [1360, 8, 707, 2, 2925, 2],
 [1360, 8, 707, 2, 2925, 2, 14],
 [1360, 8, 707, 2, 2925, 2, 14, 427],
 [1360, 8, 707, 2, 2925, 2, 14, 427, 1152],
 [1360, 8, 707, 2, 2925, 2, 14, 427, 1152, 1],
 [1360, 8, 707, 2, 2925, 2, 14, 427, 1152, 1, 506],
 [1360, 8, 707, 2, 2925, 2, 14, 427, 1152, 1, 506, 2004],
 [4, 665],
 [4, 665, 100],
 [4, 665, 100, 183],
 [4, 665, 100, 183, 11],
 [4, 665, 100, 183, 11, 74],
 [4, 665, 100, 183, 11, 74, 1573],
 [4, 665, 100, 183, 11, 74, 1573, 19],
 [4, 665, 100, 183, 11, 74, 1573, 19, 30],
 [4, 665, 100, 183, 11, 74, 1573, 19, 30, 1098],
 [4, 665, 100, 183, 11, 74, 1573, 19, 30, 1098, 45],
 [4, 665, 100, 183, 11, 74, 1573, 19, 30, 1098, 45, 146],
 [4, 27],
 [4, 27, 86],
 [4, 27, 86, 4438],
 [4, 27, 86, 4438, 60],
 [4, 27, 86, 4438, 60, 1191],
 [4, 27, 86, 4438, 60, 1191, 15932],
 [4, 27, 86, 4438, 60, 1191, 15932, 5325],
 [4, 27, 86, 4438, 60, 1191, 15932, 5325, 20],
 [4, 27, 86, 4438, 60, 1191, 15932, 5325, 20, 1],
 [4, 27, 86, 4438, 60, 1191, 15932, 5325, 20, 1, 5059],
 [4, 27, 86, 4438, 60, 1191, 15932, 5325, 20, 1, 5059, 1],
 [712, 14],
 [712, 14, 5],
 [712, 14, 5, 289],
 [712, 14, 5, 289, 713],
 [712, 14, 5, 289, 713, 356],
 [712, 14, 5, 289, 713, 356, 384],
 [712, 14, 5, 289, 713, 356, 384, 2],
 [712, 14, 5, 289, 713, 356, 384, 2, 11],
 [712, 14, 5, 289, 713, 356, 384, 2, 11, 54],
 [712, 14, 5, 289, 713, 356, 384, 2, 11, 54, 2587],
 [712, 14, 5, 289, 713, 356, 384, 2, 11, 54, 2587, 41],
 [8, 57],
 [8, 57, 8527],
 [8, 57, 8527, 269],
 [8, 57, 8527, 269, 1500],
 [8, 57, 8527, 269, 1500, 1],
 [8, 57, 8527, 269, 1500, 1, 712],
 [8, 57, 8527, 269, 1500, 1, 712, 14],
 [8, 57, 8527, 269, 1500, 1, 712, 14, 368],
 [8, 57, 8527, 269, 1500, 1, 712, 14, 368, 23],
 [8, 57, 8527, 269, 1500, 1, 712, 14, 368, 23, 248],
 [24, 23],
 [24, 23, 595],
 [24, 23, 595, 14],
 [24, 23, 595, 14, 5],
 [24, 23, 595, 14, 5, 940],
 [24, 23, 595, 14, 5, 940, 2],
 [24, 23, 595, 14, 5, 940, 2, 54],
 [24, 23, 595, 14, 5, 940, 2, 54, 2142],
 [24, 23, 595, 14, 5, 940, 2, 54, 2142, 871],
 [24, 23, 595, 14, 5, 940, 2, 54, 2142, 871, 8],
 [24, 23, 595, 14, 5, 940, 2, 54, 2142, 871, 8, 16],
 [887, 67],
 [887, 67, 3566],
 [887, 67, 3566, 12],
 [887, 67, 3566, 12, 23],
 [887, 67, 3566, 12, 23, 109],
 [887, 67, 3566, 12, 23, 109, 85],
 [887, 67, 3566, 12, 23, 109, 85, 23],
 [887, 67, 3566, 12, 23, 109, 85, 23, 50],
 [887, 67, 3566, 12, 23, 109, 85, 23, 50, 2143],
 [887, 67, 3566, 12, 23, 109, 85, 23, 50, 2143, 12],
 [887, 67, 3566, 12, 23, 109, 85, 23, 50, 2143, 12, 55],
 [350, 228],
 [350, 228, 32],
 [350, 228, 32, 59],
 [350, 228, 32, 59, 1],
 [350, 228, 32, 59, 1, 2985],
 [350, 228, 32, 59, 1, 2985, 169],
 [350, 228, 32, 59, 1, 2985, 169, 138],
 [350, 228, 32, 59, 1, 2985, 169, 138, 8],
 [350, 228, 32, 59, 1, 2985, 169, 138, 8, 169],
 [350, 228, 32, 59, 1, 2985, 169, 138, 8, 169, 12699],
 [350, 228, 32, 59, 1, 2985, 169, 138, 8, 169, 12699, 975],
 [24, 23],
 [24, 23, 444],
 [24, 23, 444, 655],
 [24, 23, 444, 655, 26],
 [24, 23, 444, 655, 26, 430],
 [24, 23, 444, 655, 26, 430, 268],
 [24, 23, 444, 655, 26, 430, 268, 11],
 [24, 23, 444, 655, 26, 430, 268, 11, 550],
 [24, 23, 444, 655, 26, 430, 268, 11, 550, 169],
 [24, 23, 444, 655, 26, 430, 268, 11, 550, 169, 1360],
 [24, 23, 444, 655, 26, 430, 268, 11, 550, 169, 1360, 2541],
 [30, 109],
 [30, 109, 36],
 [30, 109, 36, 5],
 [30, 109, 36, 5, 975],
 [30, 109, 36, 5, 975, 174],
 [30, 109, 36, 5, 975, 174, 27],
 [30, 109, 36, 5, 975, 174, 27, 975],
 [30, 109, 36, 5, 975, 174, 27, 975, 2],
 [30, 109, 36, 5, 975, 174, 27, 975, 2, 27],
 [30, 109, 36, 5, 975, 174, 27, 975, 2, 27, 147],
 [30, 109, 36, 5, 975, 174, 27, 975, 2, 27, 147, 26],
 [30, 109, 36, 5, 975, 174, 27, 975, 2, 27, 147, 26, 207],
 [30, 109, 36, 5, 975, 174, 27, 975, 2, 27, 147, 26, 207, 2703],
 [35, 19],
 [35, 19, 15933],
 [35, 19, 15933, 19],
 [35, 19, 15933, 19, 12],
 [35, 19, 15933, 19, 12, 8],
 [35, 19, 15933, 19, 12, 8, 833],
 [35, 19, 15933, 19, 12, 8, 833, 3],
 [35, 19, 15933, 19, 12, 8, 833, 3, 31],
 [35, 19, 15933, 19, 12, 8, 833, 3, 31, 1],
 [35, 19, 15933, 19, 12, 8, 833, 3, 31, 1, 712],
 [35, 19, 15933, 19, 12, 8, 833, 3, 31, 1, 712, 3693],
 [3, 85],
 [3, 85, 39],
 [3, 85, 39, 1],
 [3, 85, 39, 1, 5059],
 [3, 85, 39, 1, 5059, 67],
 [3, 85, 39, 1, 5059, 67, 168],
 [3, 85, 39, 1, 5059, 67, 168, 55],
 [3, 85, 39, 1, 5059, 67, 168, 55, 1],
 [3, 85, 39, 1, 5059, 67, 168, 55, 1, 2985],
 [3, 85, 39, 1, 5059, 67, 168, 55, 1, 2985, 650],
 [3, 85, 39, 1, 5059, 67, 168, 55, 1, 2985, 650, 11],
 [1, 847],
 [1, 847, 1],
 [1, 847, 1, 712],
 [1, 847, 1, 712, 150],
 [1, 847, 1, 712, 150, 16],
 [1, 847, 1, 712, 150, 16, 1],
 [1, 847, 1, 712, 150, 16, 1, 2985],
 [1, 847, 1, 712, 150, 16, 1, 2985, 14],
 [1, 847, 1, 712, 150, 16, 1, 2985, 14, 5],
 [1, 847, 1, 712, 150, 16, 1, 2985, 14, 5, 289],
 [1, 847, 1, 712, 150, 16, 1, 2985, 14, 5, 289, 713],
 [115, 24],
 [115, 24, 23],
 [115, 24, 23, 14],
 [115, 24, 23, 14, 132],
 [115, 24, 23, 14, 132, 151],
 [115, 24, 23, 14, 132, 151, 229],
 [115, 24, 23, 14, 132, 151, 229, 21],
 [115, 24, 23, 14, 132, 151, 229, 21, 44],
 [115, 24, 23, 14, 132, 151, 229, 21, 44, 269],
 [115, 24, 23, 14, 132, 151, 229, 21, 44, 269, 8],
 [115, 24, 23, 14, 132, 151, 229, 21, 44, 269, 8, 203],
 [147, 922],
 [147, 922, 26],
 [147, 922, 26, 976],
 [147, 922, 26, 976, 1],
 [147, 922, 26, 976, 1, 2985],
 [147, 922, 26, 976, 1, 2985, 134],
 [147, 922, 26, 976, 1, 2985, 134, 23],
 [147, 922, 26, 976, 1, 2985, 134, 23, 109],
 [147, 922, 26, 976, 1, 2985, 134, 23, 109, 152],
 [147, 922, 26, 976, 1, 2985, 134, 23, 109, 152, 384],
 [147, 922, 26, 976, 1, 2985, 134, 23, 109, 152, 384, 7816],
 [22, 5],
 [22, 5, 2182],
 [22, 5, 2182, 61],
 [22, 5, 2182, 61, 16],
 [22, 5, 2182, 61, 16, 64],
 [22, 5, 2182, 61, 16, 64, 121],
 [22, 5, 2182, 61, 16, 64, 121, 2],
 [22, 5, 2182, 61, 16, 64, 121, 2, 169],
 [22, 5, 2182, 61, 16, 64, 121, 2, 169, 1360],
 [22, 5, 2182, 61, 16, 64, 121, 2, 169, 1360, 2053],
 [33, 20],
 [33, 20, 1],
 [33, 20, 1, 1838],
 [33, 20, 1, 1838, 1128],
 [33, 20, 1, 1838, 1128, 4120],
 [33, 20, 1, 1838, 1128, 4120, 235],
 [33, 20, 1, 1838, 1128, 4120, 235, 782],
 [33, 20, 1, 1838, 1128, 4120, 235, 782, 5590],
 [33, 20, 1, 1838, 1128, 4120, 235, 782, 5590, 41],
 [33, 20, 1, 1838, 1128, 4120, 235, 782, 5590, 41, 8],
 [33, 20, 1, 1838, 1128, 4120, 235, 782, 5590, 41, 8, 207],
 [59, 1],
 [59, 1, 5326],
 [59, 1, 5326, 821],
 [59, 1, 5326, 821, 388],
 [59, 1, 5326, 821, 388, 3],
 [59, 1, 5326, 821, 388, 3, 2384],
 [59, 1, 5326, 821, 388, 3, 2384, 16],
 [59, 1, 5326, 821, 388, 3, 2384, 16, 997],
 [59, 1, 5326, 821, 388, 3, 2384, 16, 997, 2],
 [59, 1, 5326, 821, 388, 3, 2384, 16, 997, 2, 2657],
 [59, 1, 5326, 821, 388, 3, 2384, 16, 997, 2, 2657, 324],
 [67, 628],
 [67, 628, 31],
 [67, 628, 31, 1481],
 [67, 628, 31, 1481, 34],
 [67, 628, 31, 1481, 34, 60],
 [67, 628, 31, 1481, 34, 60, 1],
 [67, 628, 31, 1481, 34, 60, 1, 1914],
 [67, 628, 31, 1481, 34, 60, 1, 1914, 121],
 [67, 628, 31, 1481, 34, 60, 1, 1914, 121, 1360],
 [67, 628, 31, 1481, 34, 60, 1, 1914, 121, 1360, 8528],
 [67, 628, 31, 1481, 34, 60, 1, 1914, 121, 1360, 8528, 19],
 [6, 848],
 [6, 848, 32],
 [6, 848, 32, 10],
 [6, 848, 32, 10, 239],
 [6, 848, 32, 10, 239, 3304],
 [6, 848, 32, 10, 239, 3304, 3153],
 [6, 848, 32, 10, 239, 3304, 3153, 26],
 [6, 848, 32, 10, 239, 3304, 3153, 26, 369],
 [6, 848, 32, 10, 239, 3304, 3153, 26, 369, 2],
 [6, 848, 32, 10, 239, 3304, 3153, 26, 369, 2, 169],
 [6, 848, 32, 10, 239, 3304, 3153, 26, 369, 2, 169, 1360],
 [15934, 134],
 [15934, 134, 1005],
 [15934, 134, 1005, 19],
 [15934, 134, 1005, 19, 30],
 [15934, 134, 1005, 19, 30, 9496],
 [15934, 134, 1005, 19, 30, 9496, 5],
 [15934, 134, 1005, 19, 30, 9496, 5, 1257],
 [15934, 134, 1005, 19, 30, 9496, 5, 1257, 384],
 [15934, 134, 1005, 19, 30, 9496, 5, 1257, 384, 40],
 [15934, 134, 1005, 19, 30, 9496, 5, 1257, 384, 40, 10],
 [15934, 134, 1005, 19, 30, 9496, 5, 1257, 384, 40, 10, 385],
 [488, 770],
 [488, 770, 4],
 [488, 770, 4, 37],
 [488, 770, 4, 37, 598],
 [488, 770, 4, 37, 598, 5],
 [488, 770, 4, 37, 598, 5, 220],
 [488, 770, 4, 37, 598, 5, 220, 6738],
 [488, 770, 4, 37, 598, 5, 220, 6738, 482],
 [488, 770, 4, 37, 598, 5, 220, 6738, 482, 5327],
 [488, 770, 4, 37, 598, 5, 220, 6738, 482, 5327, 310],
 [1, 336],
 [1, 336, 18],
 [1, 336, 18, 260],
 [1, 336, 18, 260, 310],
 [1, 336, 18, 260, 310, 1719],
 [1, 336, 18, 260, 310, 1719, 121],
 [1, 336, 18, 260, 310, 1719, 121, 1360],
 [1, 336, 18, 260, 310, 1719, 121, 1360, 848],
 [1, 336, 18, 260, 310, 1719, 121, 1360, 848, 33],
 [1, 336, 18, 260, 310, 1719, 121, 1360, 848, 33, 10],
 [5591, 15935],
 [5591, 15935, 169],
 [5591, 15935, 169, 1360],
 [5591, 15935, 169, 1360, 20],
 [5591, 15935, 169, 1360, 20, 1],
 [5591, 15935, 169, 1360, 20, 1, 2443],
 [5591, 15935, 169, 1360, 20, 1, 2443, 2],
 [5591, 15935, 169, 1360, 20, 1, 2443, 2, 320],
 [5591, 15935, 169, 1360, 20, 1, 2443, 2, 320, 3],
 [5591, 15935, 169, 1360, 20, 1, 2443, 2, 320, 3, 2542],
 [5591, 15935, 169, 1360, 20, 1, 2443, 2, 320, 3, 2542, 384],
 [147, 1655],
 [147, 1655, 24],
 [147, 1655, 24, 1153],
 [147, 1655, 24, 1153, 174],
 [147, 1655, 24, 1153, 174, 384],
 [147, 1655, 24, 1153, 174, 384, 8],
 [147, 1655, 24, 1153, 174, 384, 8, 53],
 [147, 1655, 24, 1153, 174, 384, 8, 53, 474],
 [147, 1655, 24, 1153, 174, 384, 8, 53, 474, 5],
 [147, 1655, 24, 1153, 174, 384, 8, 53, 474, 5, 8529],
 [147, 1655, 24, 1153, 174, 384, 8, 53, 474, 5, 8529, 2],
 [147, 1655, 24, 1153, 174, 384, 8, 53, 474, 5, 8529, 2, 1162],
 [10, 9497],
 [10, 9497, 18],
 [10, 9497, 18, 1],
 [10, 9497, 18, 1, 679],
 [10, 9497, 18, 1, 679, 149],
 [10, 9497, 18, 1, 679, 149, 10793],
 [10, 9497, 18, 1, 679, 149, 10793, 6281],
 [10, 9497, 18, 1, 679, 149, 10793, 6281, 121],
 [10, 9497, 18, 1, 679, 149, 10793, 6281, 121, 1360],
 [10, 9497, 18, 1, 679, 149, 10793, 6281, 121, 1360, 19],
 [10, 9497, 18, 1, 679, 149, 10793, 6281, 121, 1360, 19, 6],
 [163, 1],
 [163, 1, 194],
 [163, 1, 194, 6],
 [163, 1, 194, 6, 73],
 [163, 1, 194, 6, 73, 40],
 [163, 1, 194, 6, 73, 40, 10],
 [163, 1, 194, 6, 73, 40, 10, 826],
 [163, 1, 194, 6, 73, 40, 10, 826, 2],
 [163, 1, 194, 6, 73, 40, 10, 826, 2, 1679],
 [163, 1, 194, 6, 73, 40, 10, 826, 2, 1679, 32],
 [163, 1, 194, 6, 73, 40, 10, 826, 2, 1679, 32, 4],
 [641, 12700],
 [641, 12700, 1044],
 [641, 12700, 1044, 12],
 [641, 12700, 1044, 12, 8],
 [641, 12700, 1044, 12, 8, 20],
 [641, 12700, 1044, 12, 8, 20, 1],
 [641, 12700, 1044, 12, 8, 20, 1, 464],
 [641, 12700, 1044, 12, 8, 20, 1, 464, 4],
 [641, 12700, 1044, 12, 8, 20, 1, 464, 4, 1],
 [641, 12700, 1044, 12, 8, 20, 1, 464, 4, 1, 847],
 [16, 6],
 [16, 6, 598],
 [16, 6, 598, 1],
 [16, 6, 598, 1, 154],
 [16, 6, 598, 1, 154, 635],
 [16, 6, 598, 1, 154, 635, 4],
 [16, 6, 598, 1, 154, 635, 4, 124],
 [16, 6, 598, 1, 154, 635, 4, 124, 3694],
 [16, 6, 598, 1, 154, 635, 4, 124, 3694, 5],
 [16, 6, 598, 1, 154, 635, 4, 124, 3694, 5, 1106],
 [1099, 5],
 [1099, 5, 822],
 [1099, 5, 822, 26],
 [1099, 5, 822, 26, 5],
 [1099, 5, 822, 26, 5, 279],
 [1099, 5, 822, 26, 5, 279, 121],
 [1099, 5, 822, 26, 5, 279, 121, 1360],
 [1099, 5, 822, 26, 5, 279, 121, 1360, 109],
 [1099, 5, 822, 26, 5, 279, 121, 1360, 109, 1557],
 [1099, 5, 822, 26, 5, 279, 121, 1360, 109, 1557, 39],
 [1099, 5, 822, 26, 5, 279, 121, 1360, 109, 1557, 39, 6],
 [14, 229],
 [14, 229, 52],
 [14, 229, 52, 6],
 [14, 229, 52, 6, 2212],
 [14, 229, 52, 6, 2212, 10],
 [14, 229, 52, 6, 2212, 10, 114],
 [14, 229, 52, 6, 2212, 10, 114, 71],
 [14, 229, 52, 6, 2212, 10, 114, 71, 3],
 [14, 229, 52, 6, 2212, 10, 114, 71, 3, 108],
 [14, 229, 52, 6, 2212, 10, 114, 71, 3, 108, 80],
 [41, 8],
 [41, 8, 5],
 [41, 8, 5, 8530],
 [41, 8, 5, 8530, 1106],
 [41, 8, 5, 8530, 1106, 301],
 [41, 8, 5, 8530, 1106, 301, 20],
 [41, 8, 5, 8530, 1106, 301, 20, 1],
 [41, 8, 5, 8530, 1106, 301, 20, 1, 464],
 [41, 8, 5, 8530, 1106, 301, 20, 1, 464, 4],
 [41, 8, 5, 8530, 1106, 301, 20, 1, 464, 4, 1351],
 [41, 8, 5, 8530, 1106, 301, 20, 1, 464, 4, 1351, 1044],
 [24, 41],
 [24, 41, 265],
 [24, 41, 265, 5],
 [24, 41, 265, 5, 822],
 [24, 41, 265, 5, 822, 11],
 [24, 41, 265, 5, 822, 11, 397],
 [24, 41, 265, 5, 822, 11, 397, 39],
 [24, 41, 265, 5, 822, 11, 397, 39, 50],
 [24, 41, 265, 5, 822, 11, 397, 39, 50, 6],
 [24, 41, 265, 5, 822, 11, 397, 39, 50, 6, 36],
 [24, 41, 265, 5, 822, 11, 397, 39, 50, 6, 36, 42],
 [476, 4],
 [476, 4, 12],
 [476, 4, 12, 202],
 [476, 4, 12, 202, 36],
 [476, 4, 12, 202, 36, 42],
 [476, 4, 12, 202, 36, 42, 5],
 [476, 4, 12, 202, 36, 42, 5, 2444],
 [476, 4, 12, 202, 36, 42, 5, 2444, 4],
 [476, 4, 12, 202, 36, 42, 5, 2444, 4, 1],
 [476, 4, 12, 202, 36, 42, 5, 2444, 4, 1, 273],
 [476, 4, 12, 202, 36, 42, 5, 2444, 4, 1, 273, 121],
 [1360, 2054],
 [1360, 2054, 2],
 [1360, 2054, 2, 373],
 [1360, 2054, 2, 373, 18],
 [1360, 2054, 2, 373, 18, 1],
 [1360, 2054, 2, 373, 18, 1, 1106],
 [1360, 2054, 2, 373, 18, 1, 1106, 12],
 [1360, 2054, 2, 373, 18, 1, 1106, 12, 373],
 [1360, 2054, 2, 373, 18, 1, 1106, 12, 373, 43],
 [1360, 2054, 2, 373, 18, 1, 1106, 12, 373, 43, 19],
 [1360, 2054, 2, 373, 18, 1, 1106, 12, 373, 43, 19, 121],
 [1360, 3305],
 [1360, 3305, 71],
 [1360, 3305, 71, 1],
 [1360, 3305, 71, 1, 464],
 [1360, 3305, 71, 1, 464, 2],
 [1360, 3305, 71, 1, 464, 2, 33],
 [1360, 3305, 71, 1, 464, 2, 33, 1],
 [1360, 3305, 71, 1, 464, 2, 33, 1, 1615],
 [1360, 3305, 71, 1, 464, 2, 33, 1, 1615, 6],
 [1360, 3305, 71, 1, 464, 2, 33, 1, 1615, 6, 470],
 [1360, 3305, 71, 1, 464, 2, 33, 1, 1615, 6, 470, 1],
 [1106, 11],
 [1106, 11, 10],
 [1106, 11, 10, 968],
 [1106, 11, 10, 968, 12],
 [1106, 11, 10, 968, 12, 8],
 [1106, 11, 10, 968, 12, 8, 53],
 [1106, 11, 10, 968, 12, 8, 53, 1099],
 [1106, 11, 10, 968, 12, 8, 53, 1099, 1],
 [1106, 11, 10, 968, 12, 8, 53, 1099, 1, 635],
 [1106, 11, 10, 968, 12, 8, 53, 1099, 1, 635, 16],
 [1106, 11, 10, 968, 12, 8, 53, 1099, 1, 635, 16, 9],
 [1351, 1044],
 [1351, 1044, 57],
 [1351, 1044, 57, 84],
 [1351, 1044, 57, 84, 18],
 [1351, 1044, 57, 84, 18, 1],
 [1351, 1044, 57, 84, 18, 1, 635],
 [1351, 1044, 57, 84, 18, 1, 635, 3973],
 [1351, 1044, 57, 84, 18, 1, 635, 3973, 262],
 [1351, 1044, 57, 84, 18, 1, 635, 3973, 262, 407],
 [1351, 1044, 57, 84, 18, 1, 635, 3973, 262, 407, 9498],
 [94, 2104],
 [94, 2104, 121],
 [94, 2104, 121, 1360],
 [94, 2104, 121, 1360, 230],
 [94, 2104, 121, 1360, 230, 135],
 [94, 2104, 121, 1360, 230, 135, 5],
 [94, 2104, 121, 1360, 230, 135, 5, 149],
 [94, 2104, 121, 1360, 230, 135, 5, 149, 2078],
 [94, 2104, 121, 1360, 230, 135, 5, 149, 2078, 2],
 [94, 2104, 121, 1360, 230, 135, 5, 149, 2078, 2, 222],
 [94, 2104, 121, 1360, 230, 135, 5, 149, 2078, 2, 222, 1],
 [1106, 32],
 [1106, 32, 4],
 [1106, 32, 4, 10],
 [1106, 32, 4, 10, 278],
 [1106, 32, 4, 10, 278, 19],
 [1106, 32, 4, 10, 278, 19, 6],
 [1106, 32, 4, 10, 278, 19, 6, 3305],
 [1106, 32, 4, 10, 278, 19, 6, 3305, 184],
 [1106, 32, 4, 10, 278, 19, 6, 3305, 184, 4837],
 [1106, 32, 4, 10, 278, 19, 6, 3305, 184, 4837, 6],
 [1106, 32, 4, 10, 278, 19, 6, 3305, 184, 4837, 6, 117],
 [4, 207],
 [4, 207, 671],
 [4, 207, 671, 5],
 [4, 207, 671, 5, 220],
 [4, 207, 671, 5, 220, 581],
 [4, 207, 671, 5, 220, 581, 4],
 [4, 207, 671, 5, 220, 581, 4, 6280],
 [4, 207, 671, 5, 220, 581, 4, 6280, 6],
 [4, 207, 671, 5, 220, 581, 4, 6280, 6, 8],
 [4, 207, 671, 5, 220, 581, 4, 6280, 6, 8, 1119],
 [4, 207, 671, 5, 220, 581, 4, 6280, 6, 8, 1119, 3],
 [89, 16],
 [89, 16, 304],
 [89, 16, 304, 24],
 [89, 16, 304, 24, 20],
 [89, 16, 304, 24, 20, 1],
 [89, 16, 304, 24, 20, 1, 827],
 [89, 16, 304, 24, 20, 1, 827, 4],
 [89, 16, 304, 24, 20, 1, 827, 4, 4837],
 [89, 16, 304, 24, 20, 1, 827, 4, 4837, 6280],
 [89, 16, 304, 24, 20, 1, 827, 4, 4837, 6280, 35],
 [3974, 32],
 [3974, 32, 4],
 [3974, 32, 4, 10],
 [3974, 32, 4, 10, 278],
 [3974, 32, 4, 10, 278, 69],
 [3974, 32, 4, 10, 278, 69, 124],
 [3974, 32, 4, 10, 278, 69, 124, 298],
 [3974, 32, 4, 10, 278, 69, 124, 298, 19],
 [3974, 32, 4, 10, 278, 69, 124, 298, 19, 6],
 [3974, 32, 4, 10, 278, 69, 124, 298, 19, 6, 305],
 [3974, 32, 4, 10, 278, 69, 124, 298, 19, 6, 305, 11],
 [1, 506],
 [1, 506, 454],
 [1, 506, 454, 6282],
 [1, 506, 454, 6282, 5592],
 [1, 506, 454, 6282, 5592, 6],
 [1, 506, 454, 6282, 5592, 6, 262],
 [1, 506, 454, 6282, 5592, 6, 262, 270],
 [1, 506, 454, 6282, 5592, 6, 262, 270, 2249],
 [1, 506, 454, 6282, 5592, 6, 262, 270, 2249, 16],
 [1, 506, 454, 6282, 5592, 6, 262, 270, 2249, 16, 41],
 [1, 506, 454, 6282, 5592, 6, 262, 270, 2249, 16, 41, 131],
 [3, 31],
 [3, 31, 5],
 [3, 31, 5, 425],
 [3, 31, 5, 425, 4],
 [3, 31, 5, 425, 4, 2294],
 [3, 31, 5, 425, 4, 2294, 1638],
 [3, 31, 5, 425, 4, 2294, 1638, 164],
 [3, 31, 5, 425, 4, 2294, 1638, 164, 59],
 [3, 31, 5, 425, 4, 2294, 1638, 164, 59, 164],
 [3, 31, 5, 425, 4, 2294, 1638, 164, 59, 164, 11],
 [3, 31, 5, 425, 4, 2294, 1638, 164, 59, 164, 11, 2055],
 [121, 1360],
 [121, 1360, 262],
 [121, 1360, 262, 2143],
 [121, 1360, 262, 2143, 164],
 [121, 1360, 262, 2143, 164, 46],
 [121, 1360, 262, 2143, 164, 46, 1638],
 [121, 1360, 262, 2143, 164, 46, 1638, 11],
 [121, 1360, 262, 2143, 164, 46, 1638, 11, 802],
 [121, 1360, 262, 2143, 164, 46, 1638, 11, 802, 1470],
 [121, 1360, 262, 2143, 164, 46, 1638, 11, 802, 1470, 1],
 [15936, 13],
 [15936, 13, 122],
 [15936, 13, 122, 20],
 [15936, 13, 122, 20, 764],
 [15936, 13, 122, 20, 764, 164],
 [15936, 13, 122, 20, 764, 164, 6],
 [15936, 13, 122, 20, 764, 164, 6, 422],
 [15936, 13, 122, 20, 764, 164, 6, 422, 44],
 [15936, 13, 122, 20, 764, 164, 6, 422, 44, 8],

In [34]:
max_len = max([len(x) for x in input_sequences])
max_len

38

In [35]:
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [15]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,    1,  269],
       [   0,    0,    0, ...,    1,  269,   46],
       [   0,    0,    0, ...,  269,   46, 1310],
       ...,
       [   0,    0,    0, ..., 7407,  268,   34],
       [   0,    0,    0, ...,  268,   34,    8],
       [   0,    0,    0, ...,   34,    8,   92]], dtype=int32)

In [36]:
X = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [37]:
X.shape,y.shape

((1006186, 37), (1006186,))

In [38]:
from tensorflow.keras.utils import to_categorical
# Reverting y to integer labels instead of one-hot encoding to save RAM
# The original y before to_categorical was the integer labels
y = padded_input_sequences[:,-1]

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense

model = Sequential()
model.add(Embedding(25135, 128, input_shape=(38,)))
model.add(GRU(150))
model.add(Dense(25135, activation='softmax'))

In [48]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [49]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 38, 128)        │     3,217,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_7 (GRU)                     │ (None, 150)            │       126,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 25135)          │     3,795,385 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,138,665 (27.23 MB)

 Trainable params: 7,138,665 (27.23 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
history = model.fit(X,y,epochs=10)

Epoch 1/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 369s 12ms/step - accuracy: 0.1326 - loss: 5.8736
Epoch 2/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 361s 11ms/step - accuracy: 0.1701 - loss: 5.3587
Epoch 3/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 363s 12ms/step - accuracy: 0.1861 - loss: 5.1384
Epoch 4/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 363s 12ms/step - accuracy: 0.1986 - loss: 4.9615
Epoch 5/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 364s 12ms/step - accuracy: 0.2088 - loss: 4.8124
Epoch 6/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 364s 12ms/step - accuracy: 0.2176 - loss: 4.6915
Epoch 7/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 362s 12ms/step - accuracy: 0.2249 - loss: 4.5912
Epoch 8/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 363s 12ms/step - accuracy: 0.2313 - loss: 4.5113
Epoch 9/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 362s 12ms/step - accuracy: 0.2370 - loss: 4.4488
Epoch 10/10
31444/31444 ━━━━━━━━━━━━━━━━━━━━ 362s 12ms/step - accuracy: 0.2413 - loss: 4.3992

In [27]:
import numpy as np
import time
text = "harry"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
harry and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
harry and ron
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
harry and ron were
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
harry and ron were both
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
harry and ron were both their
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
harry and ron were both their feet
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
harry and ron were both their feet and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
harry and ron were both their feet and the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
harry and ron were both their feet and the dead
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
harry and ron were both their feet and the dead of